config/routes.rb
Rails.application.routes.draw do
  root to: "questions#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  resources :questions do
    resources :answers, only: [ :create, :edit, :update, :destroy ]
  end
  resources :answers
  devise_for :users, controllers: { sessions: "users/sessions" }
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers,
  dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question

  def create
    @answer = @question.answers.build(answer_params)
    if @answer.save
      redirect_to question_path(@question), notice: "Відповідь додано."
    else
      redirect_to question_path(@question), alert: "Не вдалося додати відповідь."
    end
  end

  def edit
    @answer = Answer.find(params[:id])
  end

  def update
    @answer = Answer.find(params[:id])
    if @answer.update(answer_params)
      redirect_to @answer.question, notice: "Відповідь оновлено."
    else
      render :edit
    end
  end

  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
    redirect_to question_path(@question), notice: "Відповідь видалено."
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:content, :user_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  allow_browser versions: :modern

  before_action :authenticate_user!, unless: :devise_controller?

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || root_path
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
before_action :set_question, only: %i[update show destroy edit]

    def create
      question = Question.create(question_params)

      redirect_to question_path(question), notice: "Your new question has been created!"
    end
  def update
   @question.update(question_params)
     redirect_to question_path(@question), notice: "Save the question!"
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: "The question was deleted!"
  end

  def show
  end

  def index
    @question = Question.new
    @questions = Question.all
  end

  def new
    @question = Question.new
  end


  def edit
  end

  private
  def  question_params
    params.require(:question).permit(:body, :user_id)
  end
  def set_question
    @question = Question.find(params[:id])
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < ApplicationController
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # GET /users/sign_in
  def new
    super unless user_signed_in? # Дозволити доступ до сторінки входу, якщо вже залогінений
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inclination(count, one, few, many)
    return many if (count % 100).between?(11, 14)

    case count % 10
    when 1 then one
    when 2..4 then few
    else
      many
    end
  end
end

app/helpers/cjdequetion_helper.rb
module CjdequetionHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: [@question, @answer], local: true) do |form| %>
    <div class="answer      -container">
    <p class="title-lg"><%= form.label :content, 'Текст відповіді' %></p>
    <p><%= form.text_area :content, rows: 5 , class: 'form-text-area' %></p>
    </div>
    <p class="mt"> <%= form.submit 'Зберегти', class: 'button button button-main' %></p>
<% end %> 

app/views/answers/edit.html.erb
<div class="container"
<h2> Редагування відповіді</h2>
<%=  render 'form', answer: @answer %>



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Askme " %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="wrapper">
  
    <div class="navbar">
    <p class="tittle-sm text-bold"><%= link_to "Ask me!", root_path %> </p>
    <div>
    <% if current_user.present? %>
    <%= content_tag 'span', "#{current_user.email}", class: 'sm'%>
    <%=  link_to 'Змінити профіль', edit_user_registration_path, class: "button button-main" %>
    <%=  button_to 'Вихід', destroy_user_session_path, method: :delete, data: { confirm: 'Ви впевнені, що хочете вийти?' }, class: 'button button-main' %>
    
    <% end %>
    </div>
    </div>
      <% flash.each do |key, message| %>
        <p class="mb mt message message-<%= key %>"><%= message %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_answer.html.erb
<div class="mt-sm">
  <div class="mb-lg"><%= answer.content %></div>  
  <div>Користувач: <%= answer.user_id %></div>  
</div>

<div class="text-sm answer-footer">
  <div class="text-grey">
    <%= l(answer.created_at, format: :short) %>
  </div>

  <div style="float: right;"> 
    <!-- Посилання для редагування відповіді -->
    <%= link_to fa_icon('pencil'), edit_question_answer_path(answer.question, answer), 
        title: 'Редагувати відповідь' %> 
    
    <!-- Кнопка для видалення відповіді -->
    <%= button_to fa_icon('trash-o'), question_answer_path(answer.question, answer), 
        method: :delete, title: 'Видалити відповідь' %>
  </div>
</div>


app/views/questions/_form.html.erb
<%= form_with model: question do |form| %>
    <p><%= form.label :body, 'Текст питання' %></p>
    <p><%= form.text_area :body, rows: 5 , class: 'form-text-area' %></p>
    <p class="mt"> <%= form.label :user_id, "Ваше ім'я"%></p>
    <p><%= form.text_field :user_id, class: 'form-text-field' %></p>
    <p class="mt"> <%= form.submit 'Зберегти', class: 'button button button-main' %></p>
<% end %> 

app/views/questions/_question.html.erb
<div class="mt-sm">
  
  <div><h1><%= question.user_id%><br> </h1></div>  
 
  <p class="mb-lg">
  <div class="mb-lg"><%= question.body %></div>  
  </p>
</div>

<div class="text-sm question-footer">
  <div class="text-grey">
    <%= l(question.created_at, format: :short) %>
  </div>

  <div style="float: right;"> 
    <%= link_to fa_icon('pencil'), edit_question_path(question), 
        title: 'Edit the question' %> 
    <%= button_to fa_icon('trash-o'), question_path(question), 
        method: :delete, title: 'Delete the question' %>
  </div>
</div>

app/views/questions/edit.html.erb
  <div class="container">
    <h2 class="title-lg mb">Edit question <% @question.id %></p>

    <%= render 'form', question: @question %>

     
  </div>

 

app/views/questions/index.html.erb
<div class="header">
  <h1>Питання</h1>
  <%= link_to "Create new question", new_question_path, class: 'button button-main' %>
</div>

<div class="container">
  <%= render "form", question: @question %>
</div>

<div class="questions-summary">
  <h2 class="title-lg mb-sm">
    <%= @questions.count %> <%= inclination(@questions.count, 'питання:', 'питання:', 'питань:') %>
  </h2>
</div>

<div class="questions-item mb-lg">
  <% @questions.each do |question| %>
    <div class="question-container">
      <%= render question %>
    </div>
    <div class="questions-list mb-sm">
      <!-- Виведення відповідей до питання -->
      <h3 class="mb">Відповіді:</h3>
      <% question.answers.each do |answer| %>
        <div class="answer-container">
          <%= render 'answer', answer: answer %>
        </div>
      <% end %>

      <!-- Форма для нової відповіді -->
      <%= form_with(model: [question, question.answers.build], local: true) do |form| %>
        <p class="mb">
          <h1 class="mb">Додати відповідь: </h1>
          <%= form.label :user_id, "Ваше ім'я" %><br>
          <%= form.text_area :user_id, rows: 1, class: 'form-text-area' %>
        </p>

        <p class="mb">
          <%= form.label :content, "Текст відповіді" %><br>
          <%= form.text_area :content, rows: 5, class: 'form-text-area' %>
        </p>

        <p>
          <%= form.submit "Відповісти", class: 'button button-main' %>
        </p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/questions/new.html.erb
<div class="container">
     <h2 class="title-lg mb">New question</h2>

     <%= render 'form', question: @question %>
</div>

app/views/questions/show.html.erb
<div class="container">
  <h2 class="title-lg mb"> Question <%= @question.id %></h2>

  <%= render 'question', question: @question %>

  <p class="mt"><%= link_to "All questions", questions_path %> </p>

  <% if @question.answers.any? %>
    <h3>Існуючі відповіді:</h3>
    <% @question.answers.each do |answer| %>
      <p><%= answer.content %></p>
    <% end %>
  <% else %>
    <p>Немає відповідей на це питання.</p>
  <% end %>
</div>